### ISSUE TITLE
Add Example for invoking AzureML model from ExasolDB using UDF

### ISSUE THREAD

**Issue by MarleneKress79789** [exasol/data-science-examples#41]
Add a Jupyter Notebook example showcasing invoke a trained AzureML model from Exasol Database via UDF.
This should include all functionality and key-words.

Builds on https://github.com/exasol/data-science-examples/issues/40

Might be similar to [UseSagemakerModelFromExasol.ipynb](https://github.com/exasol/data-science-examples/blob/main/tutorials/machine-learning/python/sagemaker/UseSagemakerModelFromExasol.ipynb) .

```[tasklist]
### Tasks
- [x] make azurml endpoint
- [x] invoke endpoint from exasol udf
- [x] parse output from endpoint
- [x] load model to bucketfs
- [x] invoke local model from udf
- [x] parse output
```
